### ISSUE TITLE
How to divide low frequency and high frequency？

### ISSUE THREAD

**Issue by ys-dpc** [koshian2/OctConv-TFKeras#3]
First of all, feel the author's open source spirit, great idea!

I know that low and high frequencies are divided according to a given proportion, but how are they divided along the channel dimension? Are they divided randomly according to proportion? Or is there some other pre-processing in it?

Thank you very much.

**Comment by koshian2** [comment]
@ys-dpc 
OK, my third party repository was created before the paper author published the official. Perhaps there may be an idea that has not been taken into consideration.

Do we need pre-processing to split low and high frequencies? The answer is NO.

The low and high frequency divisions can be generated endogenously from the input of a single image.
![](https://user-images.githubusercontent.com/12977641/56614387-e1e96980-6653-11e9-8d14-6e91d05f6a03.png)
The high frequency component just use the input, and the low frequency component apply pooling (either max or avg is good) of kernel = 2 to the input.

Since OctConv can represents high-frequency and low-frequency divisions endogenously, no special pre-processing should be necessary. When I read the paper, the pre-processing on frequency division was not written.

Thank you.
