### ISSUE TITLE
Why Octave Convolution is slower than vanilla?

### ISSUE THREAD

**Issue by BlueAnthony** [koshian2/OctConv-TFKeras#8]
As titile, Octave conv. should reduces the computation, why Octave Convolution is slower than Vanilla conv. in implementation when alpha is 0.25?

**Comment by koshian2** [comment]
@BlueAnthony 
That probably means that training time get longer, right? Because neural network training has various bottlenecks and overheads, theoretical calculation time and training time may not always match. For example, a bottleneck using 1x1Conv, which is a standard computational cost reduction techniques for neural networks, may also increase training time in some cases due to the increase in layers.

The effects of OctConv can be clearly seen by looking at the prediction time of a model, especially on CPU, as I examined in this repository. Perhaps the training time on the CPU may go down straight.
With peaky devices such as GPU and particularly TPU, the increase in layers and the resulting back-prop calculation time dominates, and training time may sometime increase.
However, if we look at the prediction time in such a case, OctConv is certainly effective, and I think it is important to reducing prediction time rather than training time when considering real applications.

**Comment by BlueAnthony** [comment]
@koshian2 Thank you for ur explanation! I agree with you.
I mean the inference time get longer, but it just happens when alpha is equal to 0.25, which is similar to your GPU result.
The following images are my inference results. 
First image is inference on GPU(GTX 1080).
![keras-octave-gpu](https://user-images.githubusercontent.com/17959032/57839228-e0e1cd00-77f8-11e9-91ca-3b420b21a158.png)
Second image is inference on CPU(i7-7700HQ).
![keras-octave-cpu](https://user-images.githubusercontent.com/17959032/57839230-e0e1cd00-77f8-11e9-8ae7-52d2878f586e.png)
Again, thanks for ur explanation and it makes sense to me.
